baseurl = "/mongo-nodejs-driver/core"
languageCode = "en-us"
title = "MongoDB Node.js Core Driver"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true

# Update versions in mongodb.toml as well
[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "/api"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/christkv/mongodb-core"
