on:
  push:
    branches: [5.x]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-5x

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: mongodb
          # Example: chore(main): release 5.7.0 [skip-ci]
          # ${scope} - parenthesis included, base branch name
          pull-request-title-pattern: 'chore${scope}: release ${version} [skip-ci]'
          pull-request-header: 'Please run the release_notes action before releasing to generate release highlights'
          changelog-path: HISTORY.md
          default-branch: 5.x

      # If release-please created a release, publish to npm
       - if: ${{ true }}
        uses: actions/checkout@v3
      - if: ${{ true }}
        name: actions/setup
        uses: ./.github/actions/setup
      - if: true
        run: npm pack
        shell: bash
      - if: true
        name: Get release version and release package file name
        run: |
          PACKAGE_VERSION=$(jq '.version' package.json | tr -d '"')
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "$GITHUB_ENV"
          echo "PACKAGE_FILE=mongodb-${PACKAGE_VERSION}.tgz" >> "$GITHUB_ENV"
      - if: true
        name: Create detached signature
        uses: mongodb-labs/drivers-github-tools/garasign/gpg-sign@main
        with:
          filenames: ${{ env.PACKAGE_FILE }}
          garasign_username: ${{ secrets.GRS_CONFIG_USER1_USERNAME }}
          garasign_password: ${{ secrets.GRS_CONFIG_USER1_PASSWORD }}
          artifactory_username: ${{ secrets.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - if: true
        name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_FILE }}
          path: |
            ${{ env.PACKAGE_FILE }}
            ${{ env.PACKAGE_FILE }}.sig
          retention-days: 3
      - if: false
        run: npm publish --provenance --tag=5x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
